force-app/main/default/objects/Project_Member__c/Project_Member__c.object-meta.xml
<CustomObject>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Project Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Members</relationshipLabel>
    <relationshipName>Project_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Date_Week_Start__c.field-meta.xml
<CustomField>
    <fullName>Date_Week_Start__c</fullName>
    <label>Date Week Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet_Item__c/Timesheet_Item__c.object-meta.xml
<CustomObject>
    <label>Timesheet Item</label>
    <nameField>
        <displayFormat>TSI-{0000}</displayFormat>
        <label>Timesheet Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet_Item__c/fields/Timesheet__c.field-meta.xml
<CustomField>
    <fullName>Timesheet__c</fullName>
    <label>Timesheet</label>
    <referenceTo>Timesheet__c</referenceTo>
    <relationshipLabel>Timesheet Items</relationshipLabel>
    <relationshipName>Timesheet_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_TimeSheetReportingController.cls
@isTest
public class Test_TimeSheetReportingController {
    
    @isTest
    public static void TestReporting() {
        Project__c prj = TestDataFactory.createProject('Test Project');
        insert prj;
        Project_Member__c prjm = TestDataFactory.createProjectMember(prj);
        insert prjm;
        Timesheet__c ts = TestDataFactory.createTimesheet(prjm);
        ts.Date_Week_Start__c = TestDataFactory.getWeekStartDate(-1);
        insert ts;
        System.debug('Test_TimeSheetReportingController.TestReporting project:'+prj);
        List<Timesheet_Item__c> listTsi = [select Id, Name from Timesheet_Item__c where Timesheet__c=:ts.Id];
        System.assertEquals(listTsi.size(), 7, 'Seven timesheet items are expected to be created from TimesheetTrigger');
    }
}